version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - python -m pip install --upgrade pip

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
